version: 2
updates:
  - package-ecosystem: npm
    directory: /
    schedule:
      interval: weekly
    open-pull-requests-limit: 5
    groups:
      development-dependencies:
        dependency-type: development
    ignore:
      - dependency-name: payload
      - dependency-name: "@payloadcms/*"
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: monthly
