import { chmod, readFile, writeFile } from 'node:fs/promises'
import { randomBytes } from 'node:crypto'
import { resolve } from 'node:path'
import { getPayload } from 'payload'
import config from '../src/payload.config.js'

const root = resolve(import.meta.dirname, '..')
const tokenPath = resolve(root, '.local-mcp-token')
const adminPath = resolve(root, '.local-admin.json')

async function existingSecret(path: string): Promise<string | undefined> {
  try { return (await readFile(path, 'utf8')).trim() || undefined } catch { return undefined }
}

const payload = await getPayload({ config })
const email = 'admin@plugload.local'
const storedAdmin = await existingSecret(adminPath)
const storedToken = await existingSecret(tokenPath)
const password = storedAdmin ? JSON.parse(storedAdmin).password : randomBytes(24).toString('base64url')
const apiKey = storedToken ?? randomBytes(32).toString('base64url')

const users = await payload.find({ collection: 'users', where: { email: { equals: email } }, limit: 1, overrideAccess: true })
const user = users.docs[0] ?? await payload.create({ collection: 'users', data: { email, password, role: 'admin' }, overrideAccess: true })

const keyData = {
  user: user.id,
  label: 'Plugload local development',
  description: 'Least-privilege local key generated by the Plugload example seeder.',
  enableAPIKey: true,
  apiKey,
  posts: { find: true, create: true, update: true },
  categories: { find: true, create: true, update: true },
  siteSettings: { find: true, update: true },
  'payload-mcp-tool': {
    plugloadInspectSchema: true,
    plugloadPlanOperation: true,
    plugloadApproveOperation: true,
    plugloadApplyOperation: true,
    plugloadAuditRecent: true,
  },
  'payload-mcp-resource': { plugloadSafetyPolicy: true },
}

const keys = await payload.find({ collection: 'payload-mcp-api-keys', where: { label: { equals: keyData.label } }, limit: 1, overrideAccess: true })
if (keys.docs[0]) await payload.update({ collection: 'payload-mcp-api-keys', id: keys.docs[0].id, data: keyData, overrideAccess: true })
else await payload.create({ collection: 'payload-mcp-api-keys', data: keyData, overrideAccess: true })

await writeFile(tokenPath, `${apiKey}\n`, { mode: 0o600 })
await writeFile(adminPath, `${JSON.stringify({ email, password }, null, 2)}\n`, { mode: 0o600 })
await chmod(tokenPath, 0o600)
await chmod(adminPath, 0o600)
await payload.destroy()

process.stdout.write('Local Payload user and MCP key are ready. Credentials were saved to ignored mode-600 files.\n')
